name:                maat
version:             1.0.0.0
github:              "githubuser/inst"
license:             BSD3
author:              "Luis Fdez / Junta de Andalucia"
maintainer:          "luis.fernandez.fernandez@juntadeandalucia.es"
copyright:           "Junta de Andalucia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/inst#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- tar
- conduit
- http-conduit
- http-client
- text
- zlib
- bytestring
- directory
- clock
- aeson
- MissingH
- ansi-terminal
- monad-loops

library:
  source-dirs: src

executables:
  maat_win32:
    main:                Main.hs
    source-dirs:         win32_x86_64
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maat
    
  maat_macos:
    main:                Main.hs
    source-dirs:         macos
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maat

tests:
  maat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maat
